// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHpu4o-jgrcQ2y3WWhbVTN40Fcuhg0v6k',
    appId: '1:683245559936:web:3b250c1a180e9427078665',
    messagingSenderId: '683245559936',
    projectId: 'ponchao-2c0bd',
    authDomain: 'ponchao-2c0bd.firebaseapp.com',
    databaseURL: 'https://ponchao-2c0bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ponchao-2c0bd.appspot.com',
    measurementId: 'G-0X99BPTGM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEzcsD-CcleSpPyncC9E34daWkqR5Iqg0',
    appId: '1:683245559936:android:6f85a547525830b0078665',
    messagingSenderId: '683245559936',
    projectId: 'ponchao-2c0bd',
    databaseURL: 'https://ponchao-2c0bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ponchao-2c0bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGJ6x9GJyCFeSSuAYU_Wbw8NnLUB7plE',
    appId: '1:683245559936:ios:af1abf18232aeef9078665',
    messagingSenderId: '683245559936',
    projectId: 'ponchao-2c0bd',
    databaseURL: 'https://ponchao-2c0bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ponchao-2c0bd.appspot.com',
    iosBundleId: 'com.example.ponchaoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoGJ6x9GJyCFeSSuAYU_Wbw8NnLUB7plE',
    appId: '1:683245559936:ios:af1abf18232aeef9078665',
    messagingSenderId: '683245559936',
    projectId: 'ponchao-2c0bd',
    databaseURL: 'https://ponchao-2c0bd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ponchao-2c0bd.appspot.com',
    iosBundleId: 'com.example.ponchaoApp',
  );
}
